version: '3.8'
services:
  spark:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - SPARK_DRIVER_MEMORY=4g
      - SPARK_EXECUTOR_MEMORY=4g
    volumes:
      - .:/app
      - ../data:/data